# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-22.04"
  config.vm.box_check_update = false
  config.vm.boot_timeout = 600
  config.vm.synced_folder ".", "/vagrant", disabled: true

  # ssh
  config.ssh.forward_agent = false
  config.ssh.insert_key = false

  # VMware
  config.vm.provider "vmware_desktop" do |v|
    v.gui    = false
    v.memory = 8192
    v.cpus   = 4
  end

  config.vm.define :admin, autostart: false do |admin|
    admin.vm.hostname = "admin"
    admin.vm.network "private_network", ip: "192.168.1.100"

    admin.vm.provider "vmware_desktop" do |v|
      v.gui    = false
      v.memory = 4096
      v.cpus   = 2
    end
  end

  (1..2).each do |i|
    config.vm.define "ubuntu0#{i}", autostart: false do |worker|
      worker.vm.hostname = "ubuntu0#{i}"
      worker.vm.network "private_network", ip: "192.168.1.10#{i}"

      worker.vm.provider "vmware_desktop" do |v|
        v.gui    = false
        v.memory = 8192
        v.cpus   = 4
      end
    end
  end

end
